name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # This adds the manual trigger

jobs:
  tests:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run tests
        uses: devcontainers/ci@v0.3
        with:
          runCmd: dotnet test --no-build
        env:
          AZURE_CLIENT_ID_DEV: ${{ secrets.AZURE_CLIENT_ID_DEV }}
          AZURE_CLIENT_SECRET_DEV: ${{ secrets.AZURE_CLIENT_SECRET_DEV }}
          AZURE_TENANT_ID_DEV: ${{ secrets.AZURE_TENANT_ID_DEV }}
